"""Data access.

Two paths in:
  * `load_bars_csv` / `load_snapshot_csv` for real market data you supply.
  * `synthetic_universe` for a self-contained demo.

A serious warning about the synthetic path: it validates that the plumbing
works - detectors fire, sizing is applied, costs are charged, the journal fills
in. It proves NOTHING about whether the strategy makes money, because the data
was generated by assumptions rather than by a market. Any profit figure from
synthetic data is an artefact of the generator. Use real data before drawing a
single conclusion about edge.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

NY = "America/New_York"
BAR_COLUMNS = ["open", "high", "low", "close", "volume"]


# --------------------------------------------------------------------------
# Real data
# --------------------------------------------------------------------------

def load_bars_csv(path: str | Path, tz: str = NY) -> pd.DataFrame:
    """Load 1-minute bars: timestamp,open,high,low,close,volume."""
    df = pd.read_csv(path)
    ts_col = next((c for c in df.columns if c.lower() in
                   ("timestamp", "datetime", "date", "time")), None)
    if ts_col is None:
        raise ValueError("no timestamp column found")
    idx = pd.to_datetime(df[ts_col], utc=True).dt.tz_convert(tz)
    df = df.drop(columns=[ts_col])
    df.columns = [c.lower() for c in df.columns]
    missing = [c for c in BAR_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"missing columns: {missing}")
    return df[BAR_COLUMNS].set_index(idx).sort_index()


def load_snapshot_csv(path: str | Path) -> pd.DataFrame:
    """Load the premarket snapshot the scanner consumes."""
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


def split_sessions(df: pd.DataFrame) -> dict[pd.Timestamp, pd.DataFrame]:
    return {day: grp for day, grp in df.groupby(df.index.normalize())}


def regular_hours(df: pd.DataFrame) -> pd.DataFrame:
    return df.between_time("09:30", "16:00")


# --------------------------------------------------------------------------
# Synthetic data (demo and tests only)
# --------------------------------------------------------------------------

def _leg_path(start: float, minutes: int, total_move: float, rng, noise: float) -> np.ndarray:
    """A price path over `minutes` bars moving `total_move` in total."""
    steps = rng.normal(total_move / minutes, noise, minutes)
    return start + np.cumsum(steps)


def synthetic_session(
    date: pd.Timestamp,
    open_price: float = 5.0,
    regime: str = "trend",
    seed: int = 0,
    minutes: int = 390,
) -> pd.DataFrame:
    """One session of 1-minute bars with realistic momentum microstructure.

    Regimes:
      trend  - opening drive with pullbacks and flags (the strategy's habitat)
      fade   - pops on the open and sells off all day (the common outcome)
      chop   - directionless, whipsaws every level (the account killer)
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range(f"{date.date()} 09:30", periods=minutes, freq="1min", tz=NY)

    vol_pct = 0.010 if regime != "chop" else 0.006
    noise = open_price * vol_pct / np.sqrt(6)

    path: list[float] = []
    kinds: list[str] = []          # per-bar leg type, used for the volume profile
    price = open_price
    remaining = minutes

    # The leg plan is randomised per session. A fixed schedule is a subtle but
    # serious simulation bug: every session would place its impulses at the
    # same clock times, so any setup keyed to the clock (the opening range in
    # particular) lines up with the same part of the move every single day and
    # produces a systematic result that is an artefact of the generator rather
    # than a property of markets.
    def _legs(n_cycles, imp_pct, cons_pct, imp_bars, cons_bars):
        out = []
        for _ in range(n_cycles):
            out.append(("imp", int(rng.integers(*imp_bars)), float(rng.uniform(*imp_pct))))
            out.append(("cons", int(rng.integers(*cons_bars)), float(rng.uniform(*cons_pct))))
        return out

    if regime == "trend":
        plan = [("cons", int(rng.integers(1, 5)), float(rng.uniform(-0.01, 0.02)))]
        plan += _legs(rng.integers(3, 6), (0.03, 0.10), (-0.025, -0.005), (3, 9), (3, 10))
        plan.append(("drift", 60, float(rng.uniform(-0.05, 0.0))))
    elif regime == "fade":
        plan = [("imp", int(rng.integers(2, 6)), float(rng.uniform(0.02, 0.07)))]
        plan += _legs(rng.integers(1, 3), (0.01, 0.03), (-0.02, -0.005), (2, 5), (3, 8))
        plan.append(("drift", int(rng.integers(20, 40)), float(rng.uniform(-0.14, -0.06))))
        plan.append(("cons", 10, float(rng.uniform(0.0, 0.02))))
        plan.append(("drift", 60, float(rng.uniform(-0.10, -0.04))))
    else:
        plan = _legs(rng.integers(3, 6), (0.005, 0.02), (-0.02, -0.005), (8, 16), (8, 16))

    for kind, dur, pct in plan:
        dur = min(dur, remaining)
        if dur <= 0:
            break
        n = noise * (1.6 if kind == "imp" else 0.7 if kind == "cons" else 1.0)
        seg = _leg_path(price, dur, price * pct, rng, n)
        path.extend(seg.tolist())
        kinds.extend([kind] * dur)
        price = float(seg[-1])
        remaining -= dur

    if remaining > 0:
        seg = _leg_path(price, remaining, price * -0.01, rng, noise * 0.6)
        path.extend(seg.tolist())
        kinds.extend(["drift"] * remaining)

    close = np.maximum(np.array(path[:minutes]), 0.10)

    # Build OHLC around the closing path with an intrabar wick.
    prev = np.concatenate([[open_price], close[:-1]])
    wick = np.abs(rng.normal(0, noise * 0.8, minutes))
    high = np.maximum(prev, close) + wick
    low = np.minimum(prev, close) - wick

    # Volume: front-loaded across the session, and genuinely surging on impulse
    # legs while drying up in consolidations. Real momentum breakouts print two
    # to five times the recent average; a generator that smooths that away
    # makes any volume-confirmation rule look broken when it is not.
    base = np.linspace(1.0, 0.25, minutes) ** 2
    move = np.abs(np.diff(np.concatenate([[open_price], close])))
    move_norm = move / (move.mean() + 1e-9)
    kinds_arr = np.array((kinds + ["drift"] * minutes)[:minutes])
    leg_mult = np.where(kinds_arr == "imp", rng.uniform(2.5, 5.0, minutes),
                np.where(kinds_arr == "cons", rng.uniform(0.3, 0.6, minutes),
                         rng.uniform(0.7, 1.2, minutes)))
    volume = (base * 150_000 * leg_mult * (0.5 + move_norm)
              * rng.uniform(0.8, 1.2, minutes)).astype(int)
    volume = np.maximum(volume, 1_000)

    return pd.DataFrame(
        {"open": prev, "high": high, "low": low, "close": close, "volume": volume},
        index=idx,
    )


def synthetic_universe(
    n_days: int = 40,
    symbols_per_day: int = 2,
    seed: int = 42,
    trend_probability: float = 0.35,
) -> tuple[dict[pd.Timestamp, dict[str, pd.DataFrame]], pd.DataFrame]:
    """A demo universe plus the matching premarket snapshot.

    `trend_probability` is deliberately well below one half. Most gappers do not
    trend; assuming otherwise is the most expensive mistake available here.
    """
    rng = np.random.default_rng(seed)
    days = pd.bdate_range("2025-01-06", periods=n_days)
    sessions: dict[pd.Timestamp, dict[str, pd.DataFrame]] = {}
    snap_rows = []

    for d, day in enumerate(days):
        per_day: dict[str, pd.DataFrame] = {}
        for k in range(symbols_per_day):
            sym = f"SYM{d:02d}{k}"
            roll = rng.random()
            regime = "trend" if roll < trend_probability else ("fade" if roll < 0.75 else "chop")
            prev_close = float(rng.uniform(1.8, 12.0))
            gap = float(rng.uniform(12, 90))
            open_price = round(prev_close * (1 + gap / 100), 2)

            per_day[sym] = synthetic_session(
                day, open_price=open_price, regime=regime, seed=int(rng.integers(1e9))
            )
            snap_rows.append({
                "symbol": sym,
                "date": day,
                "price": open_price,
                "prev_close": prev_close,
                "gap_pct": gap,
                "premarket_volume": int(rng.uniform(150_000, 3_000_000)),
                "float_shares": float(rng.uniform(1.2e6, 18e6)),
                "rvol": float(rng.uniform(5, 60)),
                "has_catalyst": True,
                "is_otc": False,
                "regime": regime,
            })
        sessions[pd.Timestamp(day)] = per_day

    return sessions, pd.DataFrame(snap_rows)
